name: responsive_widget
description: Responsive Widget
version: 0.0.1
homepage: https://github.com/hchaviano/responsive_widget

environment:
  sdk: '>=2.19.4 <=3.0.0'
  flutter: '>=3.7.7'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


